== Associate an Egress IP with Namespace

Sometimes it is required to know where traffic originates from, for example Ansible Automation Platform (AAP), to allow ssh traffic from OpenShift to specific sets of nodes.

The IP will broadcasted using ARP, to let the router know that the IP is available.



To associate an IP with a namespace, we have to assign a pool of IPs to a specific namespace:

.my-project-egress-ip.yaml
----
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egress-my-project
spec:
  egressIPs:
    - 10.0.1.100
    - 10.0.1.101
    - 10.0.1.102
  namespaceSelector:
    matchLabels:
      env: egress-ssh
----

Each node has to be labeled to allow an egress ip association:

.Apply label to targeted worker nodes
----
oc label node bm214.pietersmalan.com k8s.ovn.org/egress-assignable=""
oc label node bm215.pietersmalan.com k8s.ovn.org/egress-assignable=""
oc label node bm216.pietersmalan.com k8s.ovn.org/egress-assignable=""
----

EgressIP reachability check can be configured on the Network Operator:

.cluster.yaml
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  logLevel: Normal
  operatorLogLevel: Normal
  disableNetworkDiagnostics: false
  observedConfig: null
  defaultNetwork:
    ovnKubernetesConfig:
      egressIPConfig:
        reachabilityTotalTimeoutSeconds: 5
....
----

On the namespace, add the label, env=egress-ssh, to match the selector in the sample above.

.Apply label to NameSpace
----
oc label namespace my-project dev=egress-ssh
----

Create a pod to generate some egress traffic, within the namespace:

.egress-pod.yaml
----
apiVersion: v1
kind: Pod
metadata:
  name: egress-pod
  annotations:
spec:
  containers:
  - command: ['bash', '-c', 'while true; do curl -m 5 https://google.com/test-egress.txt ; sleep 20; done']
    image: registry.redhat.io/rhel7/rhel-tools
    imagePullPolicy: IfNotPresent
    name: test-egress-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
----

To see the status of the egress IP allocation, look at the status of the EgressIP object:

.Status EgressIP
----
status:
  items:
    - egressIP: 10.0.1.100
      node: bm214.pietersmalan.com
    - egressIP: 10.0.1.102
      node: bm215.pietersmalan.com
    - egressIP: 10.0.1.101
      node: bm216.pietersmalan.com
----

.OC Command 
----
oc get eip
----

.Output
----
NAME                EGRESSIPS    ASSIGNED NODE            ASSIGNED EGRESSIPS
egress-my-project   10.0.1.100   bm214.pietersmalan.com   10.0.1.100
----

Router ARP Table:
----
[admin@HomeLab] > ip/arp/print 
Flags: D - DYNAMIC; C - COMPLETE
Columns: ADDRESS, MAC-ADDRESS, INTERFACE, STATUS
 #    ADDRESS         MAC-ADDRESS        INTERFACE  STATUS   
....  
34 DC 10.0.1.100      52:54:00:01:30:63  bridge1    stale    
35 DC 10.0.1.101      52:54:00:1C:92:9A  bridge1    reachable
36 DC 10.0.1.102      52:54:00:8D:F2:A8  bridge1    stale     
....
----


---

WARNING: Only if using seconday interface

For using the secondary interface as egress, you have to enable non-local traffic to flow through the OVNKubernetes stack, by adding *ipForwarding: Global*.

.cluster.yaml
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  logLevel: Normal
  operatorLogLevel: Normal
  disableNetworkDiagnostics: false
  observedConfig: null
  defaultNetwork:
    ovnKubernetesConfig:
      egressIPConfig: {}
      gatewayConfig:
        ipForwarding: Global
----

---

