== Recovering from Bad NNCP

If you lose network connectivity with following error message:

Error syncing pod, skipping" err="network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: no CNI configuration file in /etc/kubernetes/cni/net.d/. Has your network provider started?

=== Delete the bad nncp

oc delete nncp/policy-name

=== If no network

Edit GRUB boot command line, add an S to end of line, for single user mode.

----
password root
...
exit
----

Login in as root.

Start network with expected ip, or dhcp, using nmtui and the interface originally specified during configuration.

=== Recreate network configuration on bad nodes

Recreate the missing file on failed node, with root.

./var/run/multus/cni/net.d/10-ovn-kubernetes.conf
----
{"binDir":"/var/lib/cni/bin","cniVersion":"0.3.1","logLevel":"verbose","logToStderr":true,"name":"multus-cni-network","clusterNetwork":"/host/run/multus/cni/net.d/10-ovn-kubernetes.conf","namespaceIsolation":true,"globalNamespaces":"default,openshift-multus,openshift-sriov-network-operator,openshift-cnv","type":"multus-shim","daemonSocketDir":"/run/multus/socket"}
----

=== Restart all services

----
systemctl stop kubelet
systemctl restart crio
systemctl restart ovsdb-server.service 
systemctl restart ovs-vswitchd.service
systemctl start kubelet
----

=== Force re-render of nodes

.Execute on failed node as root
----
rm /etc/machine-config-daemon/currentconfig
touch /run/machine-config-daemon-force
reboot
----


/var/lib/kubelet/kubeconfig - 
