== Podman hosted local Assistant Installer

.Edit configmap.yml
----
IMAGE_SERVICE_BASE_URL: http://node2:8888
SERVICE_BASE_URL: http://node2:8090
----


.Run Container for Assisted Installer:
----
wget https://github.com/openshift/assisted-service/blob/master/deploy/podman/configmap.yml
wget https://github.com/openshift/assisted-service/blob/master/deploy/podman/pod-persistent.yml
podman play kube --configmap configmap.yml pod-persistent.yml 
----

TIP: Make sure to use the latest branch, https://github.com/openshift/assisted-service/blob/release-4.12/deploy/podman/README.md


== Disconnected local AI Installer

=== Get the binaries:

Install relevant binaries on connected, and disconnected hosts. For example mirror registry would only be needed on the disconnected host. 

TIP: All configuration was done for OpenShift 4.16.16. Update according to your target version.

.Install nmstatectl, get openshift binaries, and mirror registry
----
sudo dnf install -y nmstate
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz 
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.rhel9.tar.gz
tar zxvf openshift-client-linux.tar.gz
tar zxvf openshift-install-linux.tar.gz
tar zxvf oc-mirror.rhel9.tar.gz
chmod +x oc-mirror
rm *.gz
mkdir ~/mirror-registry
cd ~/mirror-registry
wget https://mirror.openshift.com/pub/cgw/mirror-registry/latest/mirror-registry-amd64.tar.gz
tar zxvf mirror-registry-amd64.tar.gz
rm *.gz
----

=== 

Download the pull secret from https://console.redhat.com/openshift/downloads and create a file pull-secret.json in home folder on the connected host. (original file, if downloaded, is pull-secret.txt)



=== Create mirror images on connected host

.imageset-config.yaml
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2

storageConfig:
  local:
    path: ./

mirror:
  platform:
    channels:
    - name: stable-4.16
      type: ocp
      minVersion: 4.16.16
      maxVersion: 4.16.16
    graph: true

  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: kubevirt-hyperconverged
      channels:
      - name: stable
        minVersion: 4.16.6
    - name: mtv-operator
      channels:
        - name: release-v2.7
    - name: lvms-operator
      channels:
        - name: stable-4.16
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable

    - name: web-terminal
      channels:
      - name: fast

    - name: cincinnati-operator
      channels:
        - name: v1

additionalImages:
  ....
  - name: quay.io/edge-infrastructure/assisted-installer-agent:latest
  - name: quay.io/edge-infrastructure/assisted-installer:latest
  - name: quay.io/edge-infrastructure/assisted-installer-controller:latest
  ....
----
==== Create or host RHCOS images

Create a web server or use an existing web server to host the required RHCOS image(s).

For creating a NGINX installation:
----
sudo dnf install -y nginx
sudo mkdir -p /usr/share/nginx/html/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3
cd /usr/share/nginx/html/pub/openshift-v4/dependencies/rhcos/4.10/4.16.3
sudo wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3/rhcos-4.16.3-x86_64-live.x86_64.iso
sudo wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3/sha256sum.txt

----

==== Create a working directory, and get the required yaml files for configuration:
----
mkdir ai
cd ai
wget https://github.com/openshift/assisted-service/raw/refs/heads/release-4.16/deploy/podman/configmap-disconnected.yml
wget https://github.com/openshift/assisted-service/raw/refs/heads/release-4.16/deploy/podman/pod-persistent-disconnected.yml
----


