== Podman hosted local Assistant Installer

.Edit configmap.yml
----
IMAGE_SERVICE_BASE_URL: http://node2:8888
SERVICE_BASE_URL: http://node2:8090
----


.Run Container for Assisted Installer:
----
wget https://github.com/openshift/assisted-service/blob/master/deploy/podman/configmap.yml
wget https://github.com/openshift/assisted-service/blob/master/deploy/podman/pod-persistent.yml
podman play kube --configmap configmap.yml pod-persistent.yml 
----

TIP: Make sure to use the latest branch, https://github.com/openshift/assisted-service/blob/release-4.12/deploy/podman/README.md


== Disconnected local AI Installer

=== Get the binaries:

Install relevant binaries on connected, and disconnected hosts. For example mirror registry would only be needed on the disconnected host. 

TIP: All configuration was done for OpenShift 4.16.16. Update according to your target version.

.Install nmstatectl, get openshift binaries, and mirror registry
----
sudo dnf install -y nmstate
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz 
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-install-linux.tar.gz
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.rhel9.tar.gz
tar zxvf openshift-client-linux.tar.gz
tar zxvf openshift-install-linux.tar.gz
tar zxvf oc-mirror.rhel9.tar.gz
chmod +x oc-mirror
rm *.gz
mkdir ~/mirror-registry
cd ~/mirror-registry
wget https://mirror.openshift.com/pub/cgw/mirror-registry/latest/mirror-registry-amd64.tar.gz
tar zxvf mirror-registry-amd64.tar.gz
rm *.gz
----

=== Quay Registry (Disconnected host)

.Open firewall for default ports (If required)
----
sudo firewall-cmd --add-port=8443/tcp --zone=public --permanent
sudo firewall-cmd --reload
----

.Setup Quay registry, replacing quayhostname to fully qualified host name, and SSL certificates :
----
cd ~/mirror-registry
sudo ./mirror-registry install --initUser quay --initPassword quayquay --quayHostname <quayhostname> --sslCert ~/certs/cert.pem --sslKey ~/certs/privkey.pem
----

Sign in to https://<quayhost>:8443 using initUser/initPassword (quay/quayquay in example) as specified above.

. Under the user icon, far right hand side, select Account Settings.
. Click on the "Generate Encrypted Password", next to "CLI Password:"
. Supply, once again, your initPassword
. Select "Docker Configuration" and download json file by clicking on "Download quay-auth.json"



=== Mirror images (Connected host)

Download the pull secret from https://console.redhat.com/openshift/downloads and create a file pull-secret.txt in home folder on the connected host. (original file, if downloaded, is pull-secret.txt)

.Reformat pull-secret in readable format, and create mirror folder to hold images
----
mkdir ~/mirror
cd ~/mirror
cat ~/pull-secret.txt | jq . >  ~/pull-secret.json
----

.Login into all the registries
----
PULL_SECRET_PATH=~/pull-secret.json
for R in $(cat $PULL_SECRET_PATH | jq -r '.auths|keys[]'); do
  echo "Logging into $R";
  U=$(jq -r ".auths.\"$R\".auth" $PULL_SECRET_PATH | base64 -d | awk -F: '{print $1}')
  P=$(jq -r ".auths.\"$R\".auth" $PULL_SECRET_PATH | base64 -d | awk -F: '{print $2}')
  podman login -u $U -p $P $R
done
----

Create a file imageset-config.yaml in mirror folder.

.imageset-config.yaml
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2

storageConfig:
  local:
    path: ./

mirror:
  platform:
    channels:
    - name: stable-4.16
      type: ocp
      minVersion: 4.16.16
      maxVersion: 4.16.16
    graph: true

  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: kubevirt-hyperconverged
      channels:
      - name: stable
        minVersion: 4.16.3
    - name: mtv-operator
      channels:
        - name: release-v2.7
    - name: local-storage-operator
      channels:
        - name: stable
    - name: lvms-operator
      channels:
        - name: stable-4.16
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable

    - name: web-terminal
      channels:
      - name: fast

    - name: cincinnati-operator
      channels:
        - name: v1

additionalImages:
  - name: quay.io/edge-infrastructure/assisted-installer-agent:latest
  - name: quay.io/edge-infrastructure/assisted-installer:latest
  - name: quay.io/edge-infrastructure/assisted-installer-controller:latest
----

NOTE: To get a list of operator names, based on channel, and version number:  
----
# Get all the channels
oc-mirror list releases --version 4.16 --channels
# For stable-4.16 Channel list operators
oc-mirror list operators --version 4.16 --channel stable-4.16 --catalogs --catalog registry.redhat.io/redhat/redhat-operator-index:v4.16
# For operator kubevirt-hyperconverged get versions
oc-mirror list operators --version 4.16 --channel stable --package kubevirt-hyperconverged --catalog registry.redhat.io/redhat/redhat-operator-index:v4.16
----

==== Create or host RHCOS images

Create a web server or use an existing web server to host the required RHCOS image(s).

For creating a NGINX installation:
----
sudo dnf install -y nginx
sudo mkdir -p /usr/share/nginx/html/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3
cd /usr/share/nginx/html/pub/openshift-v4/dependencies/rhcos/4.10/4.16.3
sudo wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3/rhcos-4.16.3-x86_64-live.x86_64.iso
sudo wget https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3/sha256sum.txt

----

==== Create a working directory, and get the required yaml files for configuration:
----
mkdir ai
cd ai
wget https://github.com/openshift/assisted-service/raw/refs/heads/release-4.16/deploy/podman/configmap-disconnected.yml
wget https://github.com/openshift/assisted-service/raw/refs/heads/release-4.16/deploy/podman/pod-persistent-disconnected.yml
----


