
== Migrate from Disconnected to Connected OpenShift Deployment

=== Update Image Registry Location 

The location of the image registry holding the images is defined within an OpenShift cluster by utilizing one or more Custom Resource Definitions (CRDs), which vary depending on the specific version of OpenShift being used.

These CRDs must be deleted, or updated if there are any specific customization done to remove any references to mirror registry.

==== ImageContentSourcePolicy (ICSP) (Deprecated since 4.14)

==== ImageDigestMirrorSet (IDMS)

==== ImageTagMirrorSet (ITMS)

=== Update Pull Secret 

Make sure that the pull secrets for the external registries like quay.io and registry.redhat.com are include in global pull secret.

.Update global pullsecret
----
oc get secret/pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' >global_pullsecret.json
oc registry login --registry="<registry>" --auth-basic="<username>:<password>" --to=global_pullsecret.json
oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=global_pullsecret.json
----

=== Update Firewall Configuration

Host names for OpenShift, allow access to port 443.

==== quay.io host names 

.CDN host names for quay.io
----
quay.io
cdn.quay.io
cdn01.quay.io
cdn02.quay.io
cdn03.quay.io
cdn04.quay.io
cdn05.quay.io
cdn06.quay.io
----

==== registry.redhat.io and update services

The Red Hat registries, registry.redhat.io and registry.access.redhat.com, return a header in the HTTP 302 redirect response which allows access only to specific content in the quay.io CDN for a short period of time. 

.Additional host names
----
access.redhat.com
registry.redhat.io
registry.access.redhat.com
registry.connect.redhat.com
api.openshift.com
mirror.openshift.com
----

==== Telemetry (Insights) and Console.redhat.com access

.Telemetry host names
----
cert-api.access.redhat.com
api.access.redhat.com
infogw.api.openshift.com
console.redhat.com
----

==== NTP servers, if using default NTP servers

.NTP Servers
----
1.rhel.pool.ntp.org
2.rhel.pool.ntp.org
3.rhel.pool.ntp.org
----






