apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  ASSISTED_SERVICE_HOST: disconnected.pietersmalan.com:8090
  ASSISTED_SERVICE_URL: https://disconnected.pietersmalan.com:8090
  HTTPS_CERT_FILE: "/etc/certs/tls.crt"
  HTTPS_KEY_FILE: "/etc/certs/tls.key"
  HTTPS_CA_FILE: "/etc/certs/ca-bundle.pem"
  ASSISTED_SERVICE_SCHEME: https
  AUTH_TYPE: none
  DB_HOST: 127.0.0.1
  DB_NAME: installer
  DB_PASS: admin
  DB_PORT: "5432"
  DB_USER: admin
  DEPLOY_TARGET: onprem
  DEPLOYMENT_TYPE: "Podman"
  DISK_ENCRYPTION_SUPPORT: "true"
  DUMMY_IGNITION: "false"
  ENABLE_SINGLE_NODE_DNSMASQ: "true"
  HW_VALIDATOR_REQUIREMENTS: '[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":10},"sno":{"cpu_cores":8,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10}}]'
  IMAGE_SERVICE_BASE_URL: https://disconnected.pietersmalan.com:8888
  IPV6_SUPPORT: "true"
  ISO_IMAGE_TYPE: "full-iso"
  LISTEN_PORT: "8888"
  NTP_DEFAULT_SERVER: ""
  OS_IMAGES: '[{"openshift_version":"4.16","cpu_architecture":"x86_64","url":"http://disconnected.pietersmalan.com/pub/openshift-v4/dependencies/rhcos/4.16/4.16.3/rhcos-4.16.3-x86_64-live.x86_64.iso","version":"4.16.16-x86_64"}]'
  POSTGRESQL_DATABASE: installer
  POSTGRESQL_PASSWORD: admin
  POSTGRESQL_USER: admin
  PUBLIC_CONTAINER_REGISTRIES: 'quay.io'
  RELEASE_IMAGES: '[{"openshift_version":"4.16","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"disconnected.pietersmalan.com:8443/416-mirror/openshift-release-dev/ocp-release:4.16.16-x86_64","version":"4.16.16","default":true}]'
  
  SERVICE_BASE_URL: https://disconnected.pietersmalan.com:8090
  STORAGE: filesystem
  ENABLE_UPGRADE_AGENT: "true"
  AGENT_DOCKER_IMAGE: "disconnected.pietersmalan.com:8443/416-mirror/edge-infrastructure/assisted-installer-agent:latest"
  CONTROLLER_IMAGE: "disconnected.pietersmalan.com:8443/416-mirror/edge-infrastructure/assisted-installer-controller:latest"
  INSTALLER_IMAGE: "disconnected.pietersmalan.com:8443/416-mirror/edge-infrastructure/assisted-installer:latest"
  SKIP_CERT_VERIFICATION: "true"
  ENABLE_OKD_SUPPORT: "false"

  additionalTrustBundle: |
    -----BEGIN CERTIFICATE-----
    MIIE9TCCA92gAwIBAgISA6LEiqLSwa1Np591TGntVm/5MA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTAwHhcNMjQxMDAzMjIyMTI1WhcNMjUwMTAxMjIyMTI0WjAdMRswGQYDVQQD
    DBIqLnBpZXRlcnNtYWxhbi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDfbrmp39/XfOS0XU/isAwbsN+j6LW4i/VnGfhc5kMUnMD18o47KpTPvM90
    B6uKLL8oD1yD+xYgk9TkDjybAs8V/f5IeNWdqP+TQ0CE9VJdmjUy7QM1PUBbx3sD
    qyO+cbZNMAQcOmef/Fwqj3QMHWg+zWe9dtiI5W/ZwhGfZF3x1DYxFibfeucnElwr
    gWNLM4W3o6MpbAtzoRpJIQkq96EsIWjlTqmVnjretJnJN+3LjCiqpQMUdkTOyT2x
    /WUHaFFicPUcGnHk4+HkIHRWi4OxBmdTRtF+s+q2NGDCRt92FuuoPVuiSo4TS+X1
    IR6qaJi9eFzOeuk5OjXnGYzZ0ZLJAgMBAAGjggIXMIICEzAOBgNVHQ8BAf8EBAMC
    BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
    HQYDVR0OBBYEFCUNR/RGyX9zUGvmlivMaEr13Zz7MB8GA1UdIwQYMBaAFLu8w0el
    5LypxsOkcgwQjaI14cjoMFcGCCsGAQUFBwEBBEswSTAiBggrBgEFBQcwAYYWaHR0
    cDovL3IxMC5vLmxlbmNyLm9yZzAjBggrBgEFBQcwAoYXaHR0cDovL3IxMC5pLmxl
    bmNyLm9yZy8wHQYDVR0RBBYwFIISKi5waWV0ZXJzbWFsYW4uY29tMBMGA1UdIAQM
    MAowCAYGZ4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYA5tIxY0B3jMEQ
    QQbXcbnOwdJA9paEhvu6hzId/R43jlAAAAGSVK7OygAABAMARzBFAiAd6CZoHBhP
    3L5fYkLxCxaeqky3OWDQ6FAi+FbFe+eHTgIhAJbqWg8ow7rARLFHsSEjN/UqihVk
    st1mrlfszNtYHLAdAHcA4JKz/AwdyOdoNh/eYbmWTQpSeBmKctZyxLBNpW1vVAQA
    AAGSVK7O2QAABAMASDBGAiEAyPc0gbjq5S1PMX+6hP5Ahr9qime4q0pB/RGnmFkp
    BEwCIQCwn/FxgVoU/s0R9KgSfC05fgB+rz2P64Z+O2E3qpVz3zANBgkqhkiG9w0B
    AQsFAAOCAQEAKng4+lGDLukOMyXGmGvS4ZRGMQIe8J+2IpvXbQEw/K1zvu75fe4D
    +SVNNVfKsntQiMvgyDf0mfreYI7v4yoipihVgV30GVmQVdqhtyZq0R6/Tw6kqSrI
    a8S1HaX5XUfGVwcN+gd2ZcPUFhnRKATgf6t6ZKH1aMOWsxnKlDgRUCi6y0mGBXED
    VFOPuXamVMDAMqlr6WFlDYIFYQePW2j4Rlzs8fg2fs6V6FGp4xWsoCLcXJW24txr
    4gFTFkEVm5KNd466xG6ejLroxnmHtqG2R7MFD+aDF1QkW2Ey2WySv6PkU0atbAnm
    c2dOkyYX1uo1vrytlX0+BkX/JlnmrTUVSg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
    Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
    Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
    bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL
    YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a
    /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4
    FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR
    mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3
    DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG
    MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/
    AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbDpHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5
    tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKG
    Fmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwBAgEwJwYD
    VR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0B
    AQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6IOmQRJWjgVzPw139vaBw1bGWKCIL0vIo
    zwzn1OZDjCQiHcFCktEJr59L9MhwTyAWsVrdAfYf+B9haxQnsHKNY67u4s5Lzzfd
    u6PUzeetUK29v+PsPmI2cJkxp+iN3epi4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p9
    1n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4XaMJgnT9x3ies7msFtpKK5bDtotij/l0
    GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLEvwRdvCn294GPDF08U8lAkIv7tghluaQh
    1QnlE4SEN4LOECj8dsIGJXpGUk3aU3KkJz9icKy+aUgA+2cP21uh6NcDIS3XyfaZ
    QjmDQ993ChII8SXWupQZVBiIpcWO4RqZk3lr7Bz5MUCwzDIA359e57SSq5CCkY0N
    4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKgRJeZ9wygIaehbHFHFhcBaMDKpiZlBHyz
    rsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP2CX7dhHov+YhD+jozLW2p9W4959Bz2Ei
    RmqDtmiXLnzqTpXbI+suyCsohKRg6Un0RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLx
    KPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77AiC/ZidstK36dRILKz7OA54=
    -----END CERTIFICATE-----
  tls-ca-bundle.pem: |
    -----BEGIN CERTIFICATE-----
    MIIE9TCCA92gAwIBAgISA6LEiqLSwa1Np591TGntVm/5MA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTAwHhcNMjQxMDAzMjIyMTI1WhcNMjUwMTAxMjIyMTI0WjAdMRswGQYDVQQD
    DBIqLnBpZXRlcnNtYWxhbi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDfbrmp39/XfOS0XU/isAwbsN+j6LW4i/VnGfhc5kMUnMD18o47KpTPvM90
    B6uKLL8oD1yD+xYgk9TkDjybAs8V/f5IeNWdqP+TQ0CE9VJdmjUy7QM1PUBbx3sD
    qyO+cbZNMAQcOmef/Fwqj3QMHWg+zWe9dtiI5W/ZwhGfZF3x1DYxFibfeucnElwr
    gWNLM4W3o6MpbAtzoRpJIQkq96EsIWjlTqmVnjretJnJN+3LjCiqpQMUdkTOyT2x
    /WUHaFFicPUcGnHk4+HkIHRWi4OxBmdTRtF+s+q2NGDCRt92FuuoPVuiSo4TS+X1
    IR6qaJi9eFzOeuk5OjXnGYzZ0ZLJAgMBAAGjggIXMIICEzAOBgNVHQ8BAf8EBAMC
    BaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAw
    HQYDVR0OBBYEFCUNR/RGyX9zUGvmlivMaEr13Zz7MB8GA1UdIwQYMBaAFLu8w0el
    5LypxsOkcgwQjaI14cjoMFcGCCsGAQUFBwEBBEswSTAiBggrBgEFBQcwAYYWaHR0
    cDovL3IxMC5vLmxlbmNyLm9yZzAjBggrBgEFBQcwAoYXaHR0cDovL3IxMC5pLmxl
    bmNyLm9yZy8wHQYDVR0RBBYwFIISKi5waWV0ZXJzbWFsYW4uY29tMBMGA1UdIAQM
    MAowCAYGZ4EMAQIBMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHYA5tIxY0B3jMEQ
    QQbXcbnOwdJA9paEhvu6hzId/R43jlAAAAGSVK7OygAABAMARzBFAiAd6CZoHBhP
    3L5fYkLxCxaeqky3OWDQ6FAi+FbFe+eHTgIhAJbqWg8ow7rARLFHsSEjN/UqihVk
    st1mrlfszNtYHLAdAHcA4JKz/AwdyOdoNh/eYbmWTQpSeBmKctZyxLBNpW1vVAQA
    AAGSVK7O2QAABAMASDBGAiEAyPc0gbjq5S1PMX+6hP5Ahr9qime4q0pB/RGnmFkp
    BEwCIQCwn/FxgVoU/s0R9KgSfC05fgB+rz2P64Z+O2E3qpVz3zANBgkqhkiG9w0B
    AQsFAAOCAQEAKng4+lGDLukOMyXGmGvS4ZRGMQIe8J+2IpvXbQEw/K1zvu75fe4D
    +SVNNVfKsntQiMvgyDf0mfreYI7v4yoipihVgV30GVmQVdqhtyZq0R6/Tw6kqSrI
    a8S1HaX5XUfGVwcN+gd2ZcPUFhnRKATgf6t6ZKH1aMOWsxnKlDgRUCi6y0mGBXED
    VFOPuXamVMDAMqlr6WFlDYIFYQePW2j4Rlzs8fg2fs6V6FGp4xWsoCLcXJW24txr
    4gFTFkEVm5KNd466xG6ejLroxnmHtqG2R7MFD+aDF1QkW2Ey2WySv6PkU0atbAnm
    c2dOkyYX1uo1vrytlX0+BkX/JlnmrTUVSg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP
    MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
    Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa
    Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF
    bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL
    YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a
    /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4
    FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR
    mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3
    DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG
    MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/
    AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbDpHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5
    tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKG
    Fmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwBAgEwJwYD
    VR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0B
    AQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6IOmQRJWjgVzPw139vaBw1bGWKCIL0vIo
    zwzn1OZDjCQiHcFCktEJr59L9MhwTyAWsVrdAfYf+B9haxQnsHKNY67u4s5Lzzfd
    u6PUzeetUK29v+PsPmI2cJkxp+iN3epi4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p9
    1n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4XaMJgnT9x3ies7msFtpKK5bDtotij/l0
    GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLEvwRdvCn294GPDF08U8lAkIv7tghluaQh
    1QnlE4SEN4LOECj8dsIGJXpGUk3aU3KkJz9icKy+aUgA+2cP21uh6NcDIS3XyfaZ
    QjmDQ993ChII8SXWupQZVBiIpcWO4RqZk3lr7Bz5MUCwzDIA359e57SSq5CCkY0N
    4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKgRJeZ9wygIaehbHFHFhcBaMDKpiZlBHyz
    rsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP2CX7dhHov+YhD+jozLW2p9W4959Bz2Ei
    RmqDtmiXLnzqTpXbI+suyCsohKRg6Un0RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLx
    KPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77AiC/ZidstK36dRILKz7OA54=
    -----END CERTIFICATE-----
  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
    [[registry]]
        prefix = ""
        location = "quay.io/openshift-release-dev"
        [[registry.mirror]]
        location = "disconnected.pietersmalan.com:8443/416-mirror/openshift-release-dev"
    [[registry]]
        prefix = ""
        location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
        [[registry.mirror]]
        location = "disconnected.pietersmalan.com:8443/416-mirror/openshift-release-dev/ocp-v4.0-art-dev"
    [[registry]]
        prefix = ""
        location = "registry.redhat.io/lvms4"
        [[registry.mirror]]
        location = "disconnected.pietersmalan.com:8443/416-mirror/lvms4"
    [[registry]]
        prefix = ""
        location = "registry.redhat.io/migration-toolkit-virtualization"
        [[registry.mirror]]
        location = "disconnected.pietersmalan.com:8443/416-mirror/migration-toolkit-virtualization"
    [[registry]]
        prefix = ""
        location = "quay.io/edge-infrastructure"
        [[registry.mirror]]
        location = "disconnected.pietersmalan.com:8443/416-mirror/edge-infrastructure"

