apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  ASSISTED_SERVICE_HOST: <disconnecthost>:8090
  ASSISTED_SERVICE_URL: https://<disconnecthost>:8090
  HTTPS_CERT_FILE: "/etc/certs/tls.crt"
  HTTPS_KEY_FILE: "/etc/certs/tls.key"
  HTTPS_CA_FILE: "/etc/certs/ca-bundle.pem"
  ASSISTED_SERVICE_SCHEME: https
  AUTH_TYPE: none
  DB_HOST: 127.0.0.1
  DB_NAME: installer
  DB_PASS: admin
  DB_PORT: "5432"
  DB_USER: admin
  DEPLOY_TARGET: onprem
  DEPLOYMENT_TYPE: "Podman"
  DISK_ENCRYPTION_SUPPORT: "true"
  DUMMY_IGNITION: "false"
  ENABLE_SINGLE_NODE_DNSMASQ: "true"
  HW_VALIDATOR_REQUIREMENTS: '[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_thresh
old_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":100,"installat
ion_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":10},"sno":{"cpu_cores":8,"ram_mib":16384,"disk_si
ze_gb":100,"installation_disk_speed_threshold_ms":10}}]'
  IMAGE_SERVICE_BASE_URL: https://<disconnecthost>:8888
  IPV6_SUPPORT: "true"
  ISO_IMAGE_TYPE: "full-iso"
  LISTEN_PORT: "8888"
  NTP_DEFAULT_SERVER: ""
  OS_IMAGES: '[{"openshift_version":"4.16","cpu_architecture":"x86_64","url":"http://<disconnecthost>/pub/openshift-v4/dependenci
es/rhcos/4.16/4.16.3/rhcos-4.16.3-x86_64-live.x86_64.iso","version":"4.16.16-x86_64"}]'
  POSTGRESQL_DATABASE: installer
  POSTGRESQL_PASSWORD: admin
  POSTGRESQL_USER: admin
  PUBLIC_CONTAINER_REGISTRIES: 'quay.io'
  RELEASE_IMAGES: '[{"openshift_version":"4.16","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"disconnected.pietersmalan.co
m:8443/416-mirror/openshift-release-dev/ocp-release:4.16.16-x86_64","version":"4.16.16","default":true}]'
  
  SERVICE_BASE_URL: https://<disconnecthost>:8090
  STORAGE: filesystem
  ENABLE_UPGRADE_AGENT: "true"
  AGENT_DOCKER_IMAGE: "<quayhost>:8443/416-mirror/edge-infrastructure/assisted-installer-agent:latest"
  CONTROLLER_IMAGE: "<quayhost>:8443/416-mirror/edge-infrastructure/assisted-installer-controller:latest"
  INSTALLER_IMAGE: "<quayhost>:8443/416-mirror/edge-infrastructure/assisted-installer:latest"
  SKIP_CERT_VERIFICATION: "true"

  registries.conf: |
    unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
    [[registry]]
        prefix = ""
        location = "quay.io/openshift-release-dev/ocp-release"
        mirror-by-digest-only = true
        [[registry.mirror]]
        location = "<quayhost>:8443/416-mirror/ocp4/openshift4"
    [[registry]]
        prefix = ""
        location = "quay.io/openshift-release-dev/ocp-v4.0-art-dev"
        mirror-by-digest-only = true
        [[registry.mirror]]
        location = "<quayhost>:8443/416-mirror/ocp4/openshift4"
