apiVersion: v1
kind: Pod
metadata:
  labels:
    app: assisted-installer
  name: assisted-installer
spec:
  containers:
  - args:
    - run-postgresql
    image: quay.io/sclorg/postgresql-12-c8s:latest
    name: db
    envFrom:
    - configMapRef:
        name: config
    volumeMounts:
      - mountPath: /var/lib/pgsql
        name: pg-data
  - image: quay.io/edge-infrastructure/assisted-installer-ui:latest
    name: ui
    ports:
    - hostPort: 8080
    securityContext:
        privileged: true
    envFrom:
    - configMapRef:
        name: config
    volumeMounts:
      - mountPath: /etc/certs
        name: certs-configmap-volume
      - mountPath: /etc/containers/certs.d/disconnected.pietersmalan.com
        name: certs-configmap-volume
  - image: quay.io/edge-infrastructure/assisted-image-service:latest
    name: image-service
    ports:
    - hostPort: 8888
    envFrom:
    - configMapRef:
        name: config
    volumeMounts:
      - mountPath: /etc/certs
        name: certs-configmap-volume
      - mountPath: /etc/containers/certs.d/disconnected.pietersmalan.com
        name: certs-configmap-volume

  - image: quay.io/edge-infrastructure/assisted-service:latest
    name: service
    ports:
    - hostPort: 8090
    envFrom:
    - configMapRef:
        name: config
