== Quay Standalone Install

:toc:
:toc-placement!:

This is a short summary on how to get Quay standalone up and running.

toc::[]

=== Prerequisites

- RHEL 8/9

- Podman

- Database MySQL / Postgresql

- Optional, but prefered, S3 storage


=== Environment Setup

.Required Packages
- podman


.Quay user
- An unix user 'quay' with admin privildges for sudo with a home folder of /home/quay.

=== Login to registry.redhat.io

Login into registry.redhat.io.

NOTE: To retrieve token, if using a shared secret, you can look it up at https://access.redhat.com/terms-based-registry/accounts

WARNING: Keep in mind, since we are running all processes as root, we need to use sudo. When authenticating against registry.redhat.io, you are authenticating the root user, no the quay user.

.Login to registry.redhat.io
----
sudo podman login -u=username -p=password registry.redhat.io
----

=== Database Configuration Postgres

.Create database directory and instance
----
sudo mkdir -p /var/lib/pgsql/data
sudo chmod 777 /var/lib/pgsql/data
sudo podman run -d --name postgresql_database \
    -v /var/lib/pgsql/data:/var/lib/pgsql/data:Z  \
    -e POSTGRESQL_USER=quayuser -e POSTGRESQL_PASSWORD=quaypass \
    -e POSTGRESQL_DATABASE=quaydb -p 5432:5432 \
    registry.redhat.io/rhel8/postgresql-13:1-109
----

.Add pg_trgm package
----
sudo podman exec -it postgresql_database /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm;" | psql -d quaydb'
sudo podman exec -it postgresql_database /bin/bash -c 'echo "ALTER USER quayuser WITH SUPERUSER;" | psql'
----

=== Redis 

.Create Redis directory and instance
----
sudo mkdir -p /var/lib/redis
sudo chmod 777 /var/lib/redis
sudo podman run -d -p 6379:6379 \
    -v /var/lib/redis:/var/lib/redis/data:Z \
    registry.redhat.io/rhel8/redis-5
----

=== S3 Storage Config (Optional)

Quay can be configured to use local file system, but performance might not be up to standard.

Create a bucket for image storage for example, "quay1"

NOTE: If S3 provider is not listed, for example MINIO without SSL enabled, use CEPH RadosGW. 


=== Quay Configuration

The Quay configuration is done though a config.yaml. The easiest way to create the config.yaml is to use the Quay configuration Wizard.

.Setup Mode (where my-secret-password is the password to access 
----
sudo podman run --rm -it --name quay_config -p 8080:8080 registry.redhat.io/quay/quay-rhel8:v3.12.2 config my-secret-password
----

==== Do the configuration through browser

Open http://localhost:8080/ (or hostname:8080 if not local quay host browser) and supply 'quayconfig' and 'my-secret-password' specified as last parameter above.

Fill in all the parameters, and click on 'Validate Configuration Changes' to check connectivity to external services, only exception is Claire.

If you want to utilize Claire, make sure to fill in the Security Endpoit Scanner, and click on 'Generate PSK'

When validation is successful, down load the config bundle.

NOTE: For reference, the config.yaml can be used to fill in the values:

.config.yaml
----
ACTION_LOG_ARCHIVE_LOCATION: west
ACTION_LOG_ARCHIVE_PATH: /logs
ACTION_LOG_ROTATION_THRESHOLD: 1w
ALLOW_PULLS_WITHOUT_STRICT_LOGGING: true
ALLOWED_OCI_ARTIFACT_TYPES:
    application/vnd.oci.image.config.v1+json:
        - application/vnd.oci.image.layer.v1.tar+zstd
    application/vnd.sylabs.sif.config.v1+json:
        - application/vnd.sylabs.sif.layer.v1+tar
AUTHENTICATION_TYPE: Database
AVATAR_KIND: local
BUILDLOGS_REDIS:
    host: quay1.pietersmalan.com
    port: 6379
DATABASE_SECRET_KEY: ff0638b7-9abf-4227-93cb-322257272c78
DB_CONNECTION_ARGS: {}
DB_URI: postgresql://quayuser:quaypass@quay1.pietersmalan.com/quaydb
DEFAULT_TAG_EXPIRATION: 2w
DISTRIBUTED_STORAGE_CONFIG:
    west:
        - RadosGWStorage
        - access_key: 29a7kI0PIaZyAMSCYW8O
          bucket_name: quay1
          hostname: minio.pietersmalan.com
          is_secure: false
          port: "9000"
          secret_key: 93o6h4WKGSseHRzHoJSPGNhpQrstf5I5cRFcmpfG
          storage_path: /datastorage/registry
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - west
EXTERNAL_TLS_TERMINATION: false
FEATURE_ACI_CONVERSION: false
FEATURE_ACTION_LOG_ROTATION: true
FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: true
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_BITBUCKET_BUILD: false
FEATURE_BLACKLISTED_EMAILS: false
FEATURE_BUILD_SUPPORT: true
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_EXTENDED_REPOSITORY_NAMES: true
FEATURE_FIPS: false
FEATURE_GITHUB_BUILD: false
FEATURE_GITHUB_LOGIN: false
FEATURE_GITLAB_BUILD: false
FEATURE_GOOGLE_LOGIN: false
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_MAILING: false
FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_PROXY_STORAGE: false
FEATURE_PROXY_CACHE: true
FEATURE_REPO_MIRROR: true
FEATURE_REQUIRE_TEAM_INVITE: true
FEATURE_RESTRICTED_V1_PUSH: true
FEATURE_SECURITY_NOTIFICATIONS: false
FEATURE_SECURITY_SCANNER: true
FEATURE_STORAGE_REPLICATION: true
FEATURE_TEAM_SYNCING: false
FEATURE_UI_V2: true
FEATURE_USER_CREATION: true
FEATURE_USER_LAST_ACCESSED: true
FEATURE_USER_LOG_ACCESS: false
FEATURE_USER_METADATA: false
FEATURE_USER_RENAME: false
FEATURE_USERNAME_CONFIRMATION: true
FRESH_LOGIN_TIMEOUT: 10m
GITHUB_LOGIN_CONFIG: {}
GITHUB_TRIGGER_CONFIG: {}
GITLAB_TRIGGER_KIND: {}
LDAP_ALLOW_INSECURE_FALLBACK: false
LDAP_EMAIL_ATTR: mail
LDAP_UID_ATTR: uid
LDAP_URI: ldap://localhost
LOG_ARCHIVE_LOCATION: default
LOGS_MODEL: database
LOGS_MODEL_CONFIG: {}
MAIL_DEFAULT_SENDER: support@quay.io
MAIL_PORT: 587
MAIL_USE_AUTH: false
MAIL_USE_TLS: false
PREFERRED_URL_SCHEME: https
REGISTRY_TITLE: Project Quay
REGISTRY_TITLE_SHORT: Project Quay
REPO_MIRROR_INTERVAL: 30
REPO_MIRROR_TLS_VERIFY: true
SEARCH_MAX_RESULT_PAGE_COUNT: 10
SEARCH_RESULTS_PER_PAGE: 10
SECRET_KEY: 318f914f-0b11-49ac-9b70-61124c18092c
SECURITY_SCANNER_INDEXING_INTERVAL: 30
SECURITY_SCANNER_V4_ENDPOINT: http://quay1.pietersmalan.com:9999
SECURITY_SCANNER_V4_PSK: YzQ5aDFiYTkxMWg0
SERVER_HOSTNAME: quay1.pietersmalan.com
SETUP_COMPLETE: true
SUPER_USERS:
    - quayadmin
TAG_EXPIRATION_OPTIONS:
    - 0s
    - 1d
    - 1w
    - 2w
    - 4w
TEAM_RESYNC_STALE_TIME: 30m
TESTING: false
USE_CDN: false
USER_EVENTS_REDIS:
    host: quay1.pietersmalan.com
    port: 6379
USER_RECOVERY_TOKEN_LIFETIME: 30m
USERFILES_LOCATION: west

----

==== Extract the configuration

.Copy quay-config.tar.gz to quay host if not local
----
scp quay-config.tar.gz quay@quay1:~
----

.Extract on quay host
----
cd
mkdir storage
mkdir config
cd config
tar zxvf ../quay-config.tar.gz
----

==== Stop the quay_config container

You can now exit the quay_config container, by pressing CTRL-C a couple times in the terminal.

==== Reconfiguration

If you want to reconfigure quay, you can restart the configuration wizard, this time pointing to config directory:

.Quay configuration pod
----
sudo podman run --rm -it --name quay_config \
  -p 8080:8080 \
  -v /home/quay/config:/conf/stack:Z \
  registry.redhat.io/quay/quay-rhel8:v3.12.2 config my-secret-password
----

NOTE: This process can also be used to short cut the typing, by editing the supplied yaml with your custom values, and copy it to quay/config and starting the wizard. 

=== Configuring Clair

==== Folder Structure

.Create folders for Clair
----
mkdir /home/quay/postgres-clairv4
setfacl -m u:26:-wx /home/quay/postgres-clairv4
sudo mkdir -p /etc/opt/clairv4/config/
----

==== Clair Postgres Database

.Configure Postgres
----
sudo podman run -d --name postgresql-clairv4 \
  -e POSTGRESQL_USER=clairuser \
  -e POSTGRESQL_PASSWORD=clairpass \
  -e POSTGRESQL_DATABASE=clair \
  -e POSTGRESQL_ADMIN_PASSWORD=adminpass \
  -p 5433:5432 \
  -v /home/quay/postgres-clairv4:/var/lib/pgsql/data:Z \
  registry.redhat.io/rhel8/postgresql-13:1-109
sudo podman exec -it postgresql-clairv4 /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"" | psql -d clair -U postgres'
----

==== Clair Configuration

NOTE: Replace your PSK key with the one /home/quay/config/config.yaml as generated.

.Configure Clair
----
cd
cat <<EOF > clair_config.yaml
http_listen_addr: :9999
introspection_addr: :9998
log_level: debug
indexer:
  connstring: host=quay1.pietersmalan.com port=5433 dbname=clair user=clairuser password=clairpass sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: host=quay1.pietersmalan.com port=5433 dbname=clair user=clairuser password=clairpass sslmode=disable
  max_conn_pool: 100
  migrations: true
  indexer_addr: clair-indexer
notifier:
  connstring: host=quay1.pietersmalan.com port=5433 dbname=clair user=clairuser password=clairpass sslmode=disable
  delivery_interval: 1m
  poll_interval: 5m
  migrations: true
auth:
  psk:
    key: "YzQ5aDFiYTkxMWg0"
    iss: ["quay"]
# tracing and metrics
trace:
  name: "jaeger"
  probability: 1
  jaeger:
    agent:
      endpoint: "localhost:6831"
    service_name: "clair"
metrics:
  name: "prometheus"

EOF

sudo cp clair_config.yaml /etc/opt/clairv4/config/config.yaml
----

==== Start Clair 

.Start Clair container
----
sudo podman run -d --name clairv4 \
-p 9999:9999 -p 9998:9998 \
-e CLAIR_CONF=/clair/config.yaml \
-e CLAIR_MODE=combo \
-v /etc/opt/clairv4/config:/clair:Z \
registry.redhat.io/quay/clair-rhel8:v3.12.2
----

=== Additional Configuration

==== Enable features in Quay

.Edit config.yaml to enable V2 UI, by adding configuration for example, 'FEATURE_UI_V2: true' 
----
cd
vi config/config.yaml
----

Enable V2 UI::

FEATURE_UI_V2: true

Enable Proxy Cache, aka pull through cache::

FEATURE_PROXY_CACHE: true

=== Finally automate restart of all Quay components

.Start Quay components with automatic restart feature
----
sudo podman run --replace --restart=always -d --name postgresql_database \
    -v /var/lib/pgsql/data:/var/lib/pgsql/data:Z  \
    -e POSTGRESQL_USER=quayuser -e POSTGRESQL_PASSWORD=quaypass \
    -e POSTGRESQL_DATABASE=quaydb -p 5432:5432 \
    registry.redhat.io/rhel8/postgresql-13:1-109

sudo podman run --replace --restart=always -d --name redis -p 6379:6379 \
    -v /var/lib/redis:/var/lib/redis/data:Z \
    registry.redhat.io/rhel8/redis-5

sudo podman run --replace --restart=always -d --name postgresql-clairv4 \
  -e POSTGRESQL_USER=clairuser \
  -e POSTGRESQL_PASSWORD=clairpass \
  -e POSTGRESQL_DATABASE=clair \
  -e POSTGRESQL_ADMIN_PASSWORD=adminpass \
  -p 5433:5432 \
  -v /home/quay/postgres-clairv4:/var/lib/pgsql/data:Z \
  registry.redhat.io/rhel8/postgresql-13:1-109

sudo podman run --replace --restart=always -d --name clairv4 \
-p 9999:9999 -p 9998:9998 \
-e CLAIR_CONF=/clair/config.yaml \
-e CLAIR_MODE=combo \
-v /etc/opt/clairv4/config:/clair:Z \
registry.redhat.io/quay/clair-rhel8:v3.12.2

sudo podman run --replace --name quay --restart=always -p 443:8443 -p 80:8080 \
   -e QUAY_DISTRIBUTED_STORAGE_PREFERENCE=west \
   --sysctl net.core.somaxconn=4096 \
   --privileged=true \
   -v /home/quay/config:/conf/stack:Z \
   -v /home/quay/storage:/datastorage:Z \
   -d registry.redhat.io/quay/quay-rhel8:v3.12.2

sudo systemctl enable --now podman-restart.service
sudo systemctl enable --now podman.service
----

==== Mirror Workers

.podman command
----
sudo podman run -d --name mirroring-worker --restart=always \
  -v /home/quay/config:/conf/stack:Z \
  registry.redhat.io/quay/quay-rhel8:v3.12.2 repomirror
----
