== Configure Fail over and General Maintenance

=== Operators

==== Node Maintenance

Gives a programmatic way of putting hosts in maintenance mode, with added functionality in the console.

.Subscription fro Operator
----
---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-workload-availability
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-maintenance-operator
  namespace: openshift-workload-availability
spec:
  channel: stable
  installPlanApproval: Automatic
  name: node-maintenance-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
----

NOTE: No extra configuration required for the operator.

.Put a node in maintenance
----
apiVersion: nodemaintenance.medik8s.io/v1beta1
kind: NodeMaintenance
metadata:
  name: nodemaintenance-sample
spec:
  nodeName: node02
  reason: "Test node maintenance"
----

.Querying the status/progress of the drain process
----
oc get nm nodemaintenance-sample
----

NOTE: There is also the capability added to console under Compute->Nodes->Node under Actions, Start Maintenance.

==== Node Health Check / Self Node Remediation

Allows a manual configuration to pick up any host issues, earlier than the standard kubernetes time outs.

===== Self Node Remediation

.Operator Subscription
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: self-node-remediation
  namespace: openshift-workload-availability
spec:
  channel: stable
  installPlanApproval: Automatic
  name: self-node-remediation
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: self-node-remediation.v0.10.0
----

.Default Self Node Remediation Configuration
----
apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationConfig
metadata:
  name: self-node-remediation-config
  namespace: openshift-workload-availability
spec:
  apiServerTimeout: 5s
  peerApiServerTimeout: 5s
  hostPort: 30001
  isSoftwareRebootEnabled: true
  watchdogFilePath: /dev/watchdog
  peerDialTimeout: 5s
  peerUpdateInterval: 15m
  apiCheckInterval: 15s
  peerRequestTimeout: 5s
  maxApiErrorThreshold: 3
----

==== Node Health Check Operator

.Node Check Operator Subscription
----
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-healthcheck-operator
  namespace: openshift-workload-availability
spec:
  channel: stable
  installPlanApproval: Automatic
  name: node-healthcheck-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: node-healthcheck-operator.v0.9.0
----

==== Kube Descheduler

.Descheduler configuration
----
apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: cluster
  namespace: openshift-kube-descheduler-operator
  resourceVersion: '31779572'
  uid: b4d7f1cf-a7df-4549-be2a-7557ffde7270
spec:
  logLevel: Normal
  mode: Automatic
  operatorLogLevel: Normal
  deschedulingIntervalSeconds: 60
  profileCustomizations:
    devEnableEvictionsInBackground: true
  observedConfig:
    servingInfo:
      cipherSuites:
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      minTLSVersion: VersionTLS12
  profiles:
    - EvictPodsWithPVC
    - DevKubeVirtRelieveAndMigrate
  managementState: Managed
  unsupportedConfigOverrides: null
----

NOTE: If using Virtualization, then the "profileCustomizations: devEnableEvictionsInBackground: true" is a required setting

=== Firmware
