== Disconnected / Pullthrough Mirror

=== Agent Config Service

The following script requires two input files, registries.conf (standard TOML format) and fullchain.pem, certificate bundle in pem format.


[,bash]
.mirror-registries-config.sh
----
#!/bin/bash
cat > registries-config.yaml << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registries
  namespace: multicluster-engine
  labels:
    app: assisted-service
data:
  ca-bundle.crt: |
$(sed 's/^/        /' fullchain.pem)

registries.conf: |
$(sed 's/^/        /' registries.conf)

EOF

oc get agentserviceconfig agent -o yaml --show-managed-fields=false > agent-service.yaml.tmp

sed '/spec:/a\ \ mirrorRegistryRef:\n    name: mirror-registries' agent-service.yaml.tmp > agent-service.yaml
----


.Apply generated yaml files
----
oc apply -f registry.yaml
oc apply -f agent-service.yaml
----



.registries.conf Sample
....
unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
short-name-mode = ""

[[registry]]
  prefix = ""
  location = "docker.io"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/dockeriocache"

[[registry]]
  prefix = ""
  location = "quay.io"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/cachequayio"

[[registry]]
  prefix = ""
  location = "registry.redhat.io"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/registryredhatiocache"
....

.Resulting /etc/containers/registries.conf on *installed nodes*:
----
[[registry]]
location = "docker.io"
insecure = false
mirror-by-digest-only = true

[[registry.mirror]]
location = "quay.pietersmalan.com/dockeriocache"
insecure = false


[[registry]]
location = "quay.io"
insecure = false
mirror-by-digest-only = true

[[registry.mirror]]
location = "quay.pietersmalan.com/cachequayio"
insecure = false


[[registry]]
location = "registry.redhat.io"
insecure = false
mirror-by-digest-only = true

[[registry.mirror]]
location = "quay.pietersmalan.com/registryredhatiocache"
insecure = false


----

=== Setup Image Tag after install

[,yaml]
.imagetagdigestmirror.yaml
----
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: image-tag-mirror
spec:
  imageTagMirrors:
  - mirrorSourcePolicy: AllowContactingSource
    mirrors:
    - quay.pietersmalan.com/cachequayio 
    source: quay.io
  - mirrorSourcePolicy: AllowContactingSource
    mirrors:
    - quay.pietersmalan.com/registryredhatiocache
    source: registry.redhat.io
  - mirrorSourcePolicy: AllowContactingSource
    mirrors:
    - quay.pietersmalan.com/dockeriocache
    source: docker.io
----

Result after apply above yaml /etc/containers/registries.conf
----
unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
short-name-mode = ""

[[registry]]
  prefix = ""
  location = "docker.io"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/dockeriocache"
    pull-from-mirror = "digest-only"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/dockeriocache"
    pull-from-mirror = "tag-only"

[[registry]]
  prefix = ""
  location = "quay.io"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/cachequayio"
    pull-from-mirror = "digest-only"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/cachequayio"
    pull-from-mirror = "tag-only"

[[registry]]
  prefix = ""
  location = "registry.redhat.io"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/registryredhatiocache"
    pull-from-mirror = "digest-only"

  [[registry.mirror]]
    location = "quay.pietersmalan.com/registryredhatiocache"
    pull-from-mirror = "tag-only"
----
