apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  labels:
    app.kubernetes.io/created-by: lightspeed-operator
    app.kubernetes.io/instance: olsconfig-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: olsconfig
    app.kubernetes.io/part-of: lightspeed-operator
  name: cluster
spec:
  llm:
    providers:
      - credentialsSecretRef:
          name: credentials
        models:
          - name: 'llama3:latest'
        name: OpenAI
        type: openai
        url: 'http://ollama.pietersmalan.com:11434/v1/'
  ols:
    conversationCache:
      redis:
        credentialsSecret: lightspeed-redis-secret
        maxMemory: 1024mb
        maxMemoryPolicy: allkeys-lru
      type: redis
    defaultModel: llama3
    defaultProvider: OpenAI
    deployment:
      replicas: 1
    logLevel: INFO
