== Redfish for Kubevirt

=== kcli utitlities

kcli allows you to create a Redfish enabled wrapper for KubeVirt.

More info at https://kcli.readthedocs.io/en/latest/#

=== Enabling a Redfish deployment within a cluster

==== Prerequisites
- A running KubeVirt cluster
- A target namesapce to deploy/manage VMS
- A kubeconfig with access to the cluster

==== Deploying the Redfish Wrapper

===== Config Map for ksusy configuration

.ksushy-configmap.yaml
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: kcli-config
  namespace: ksushy
data:
  config.yml: |+
    default:
     client: vms

    vms:
     type: kubevirt
     kubeconfig: /.kcli/kubeconfig
     enabled: true
     host: api.ocp.pietersmalan.com
     port: 6443
     namespace: vms

  kubeconfig: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: 
        ...
        server: https://api.ocp.pietersmalan.com:6443
      name: ocp
    contexts:
    - context:
        cluster: ocp
        user: admin
      name: admin
    current-context: admin
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: 
        ...
        client-key-data:
        ....
----

NOTE: The kubeconfig above is truncated. Please ensure you have the full kubeconfig content in the config map. 

NOTE: The default points to the vms namespace, but you can add multiple entries for different namespaces. Each namespace will become a "System" in Redfish. (In above example - http://ksushy.apps.ocp.pietersmalan.com/redfish/v1/Systems/vms )



===== Deployment of ksushy container

.ksushy-deployment.yaml
[source,yaml]
----
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kcli
  namespace: ksushy
  labels:
    app: kcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcli
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kcli
      annotations:
        openshift.openshift.io/restartedAt: '2025-10-03T18:56:58.515Z'
    spec:
      volumes:
        - name: kcli-config
          configMap:
            name: kcli-config
            defaultMode: 420
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: container
          command:
            - /usr/local/bin/ksushy
            - '-c'
          env:
            - name: KSUSHY_LISTEN_PORT
              value: '8080'
            - name: KSUSHY_USER
              value: admin
            - name: KSUSHY_PASSWORD
              value: admin
            - name: KSUSHY_DEBUG
              value: 'true'
            - name: KSUSHY_BOOTONCE
              value: 'true'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kcli-config
              mountPath: /.kcli
          terminationMessagePolicy: File
          image: quay.io/karmab/kcli
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
----

NOTE: The username and password are admin/admin in the example above, using environment variables.

.service.yaml
[source,yaml]
----
kind: Service
apiVersion: v1
metadata:
  name: ksushy-service
  namespace: ksushy
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: kcli
----

.route.yaml
[source,yaml]
----
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ksushy
  namespace: ksushy
  annotations:
    openshift.io/host.generated: 'true'
spec:
  #host: ksushy.apps.ocp.pietersmalan.com
  to:
    kind: Service
    name: ksushy-service
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
----

==== Accessing the Redfish endpoint

https://ksushy.apps.ocp.pietersmalan.com/redfish/v1

NOTE: The username and password are admin/admin as per the deployment above. 



== Things to add at later stage
- Convert authentication to service account. 
- Add TLS configuration support
- Add support for multiple namespaces (Systems), autogenerated by acces for SA account.
