== Agent Installer


=== Get all the relevant binaries

.Download binaries
----
OCP_VERSION=4.16.16
ARCH=x86_64
curl -k https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_VERSION/openshift-client-linux.tar.gz -o oc.tar.gz
tar zxf oc.tar.gz
curl -k https://mirror.openshift.com/pub/openshift-v4/clients/ocp/$OCP_VERSION/openshift-install-linux.tar.gz -o openshift-install-linux.tar.gz
tar zxvf openshift-install-linux.tar.gz
ISO_URL=$(./openshift-install coreos print-stream-json | grep location | grep $ARCH | grep iso | cut -d\" -f4)
curl -L $ISO_URL -o rhcos-live.iso
curl https://mirror.openshift.com/pub/openshift-v4/clients/butane/latest/butane-amd64 -o butane
curl https://mirror.openshift.com/pub/openshift-v4/clients/coreos-installer/latest/coreos-installer_amd64 -o coreos-installer
chmod +x coreos-installer 
chmod +x butane
---- 

== Single Node 

=== Create install-config.yaml

.install-config.yaml
----
apiVersion: v1
baseDomain: <domain> 
compute:
- name: worker
  replicas: 0 
controlPlane:
  name: master
  replicas: 1 
metadata:
  name: <name> 
networking: 
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16 
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
bootstrapInPlace:
  installationDisk: /dev/disk/by-id/<disk_id> 
pullSecret: '<pull_secret>' 
sshKey: |
  <ssh_key> 
imageDigestSources:
  - mirrors:
    - mirror: <repostiry>:<repository_port>/<mirror_repo>
    source: quay.io

----

NOTE: To determine /dev/disk/by-id/<disk_id>, boot rhcos-live.iso on target machine. Do a 'lsblk -o model,size,path' and detremine drive. (or you can specify /dev/sdX format).

NOTE: Be sure to include mirror registry's secret in the pullSecret.

=== Create ISO - DHCP Configuration

.Create ISO
----
mkdir sno
cp install-config.yaml sno
./openshift-install --dir=sno create single-node-ignition-config
#alias coreos-installer='podman run --privileged --pull always --rm -v /dev:/dev -v /run/udev:/run/udev -v $PWD:/data -w /data quay.io/coreos/coreos-installer:release'
coreos-installer iso ignition embed -fi sno/bootstrap-in-place-for-live-iso.ign -o sno-install.iso rhcos-live.iso.org
----

==== Create ISO - Static Network

.Install "nmstatectl"
----
sudo dnf install /usr/bin/nmstatectl -y
----

Boot rhcos-live.iso on target machine, do a "sudo nmtui" to configure network as required.

.Capture nmstate on taget machine
----
nmstatectl show > nmstate.config
----

Create install-config.yaml and agent-config.yaml


.install-config.yaml
----
apiVersion: v1
baseDomain: <base-domain> 
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0 
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1 
metadata:
  name: <cluster-name>
networking: 
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.100.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: ''
sshKey: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPHOkTjC/ErGlk/jjjl0kFeT2ypOojwwLWtdcnXcRqAz ai@disconnected.pietersmalan.com
imageDigestSources:
- mirrors:
  - <mirror-registry>/<mirror-repo>/openshift4/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
- mirrors:
  - <mirror-registry>/<mirror-repo>/openshift4/openshift/release-images
  source: quay.io/openshift-release-dev/ocp-release
additionalTrustBundle: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----

----



.agent-config-yaml
----
apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: <cluster-name>
rendezvousIP: 192.168.100.3 
hosts:
  - hostname: <cluster-name>.<base-domain>
    rootDeviceHints: 
      deviceName: /dev/sda
    interfaces:
      - name: enp1s0
        macAddress: 52:54:00:D8:43:65 
    networkConfig:
      interfaces:
        - name: enp1s0
          type: ethernet
          state: up
          mac-address: 52:54:00:D8:43:65
          ipv4:
            enabled: true
            address:
              - ip: 192.168.100.3
                prefix-length: 23 
            dhcp: false
      dns-resolver:
        config:
          server:
          - 192.168.100.249
      routes:
        config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.100.249 
          next-hop-interface: enp1s0
          table-id: 254

----

.Create manifests
----
mkdir sno
cp agent-config.yaml install-config.yaml sno
./openshift-install agent create cluster-manifests --dir sno
----

Update manifests to reflect image registry
----
cd sno/mirror
vi registries.conf
----

.Add registry.redhat.io entry:
----
[[registry]]
  prefix = ""
  location = "registry.redhat.io"
 
  [[registry.mirror]]
    location = "disconnected.pietersmalan.com:8443/mirror/ocp"
    pull-from-mirror = "digest-only"
 
  [[registry.mirror]]
    location = "disconnected.pietersmalan.com:8443/mirror/ocp"
    pull-from-mirror = "tag-only"

----

.Create ISO
----
./openshift-install --dir <install_directory> agent create image
----

Wait until server reboots.

=== Apply mirror yaml

Last step is to install the mirror generated yamls.

.Connecting to server
----
export KUBECONFIG=sno/auth/kubeconfig
----

.Checking status
----
oc get co -wA
----

Wait until all cluster operators are installed. The message column indicates the status.

Apply the yaml generated by mirror command.

==== Mirror v1

.Mirror v1 (default oc mirror) Locate the yaml under the mirror directory, for example, mirror/oc-mirror-workspace/results-...
----
oc apply -f imageContentSourcePolicy.yaml
----

Before applying catalogSource-cs-redhat-operator-index.yaml, edit the file and change the name to redhat-operator-index
----
name: redhat-operator-index
----

.Apply the changed yaml
----
oc apply -f catalogSource-cs-redhat-operator-index.yaml
----
