== Mirror using oc-mirror v2

NOTE: Still in tech-preview

NOTE: Although Quay is referenced, any Docker V2 registry would work.


Setup environment

.Install requirements
----
sudo dnf install -y nmstate
mkdir ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
tar zxvf openshift-client-linux.tar.gz
----

.env.sh
----
export QUAY_HOST_NAME=quayhostname
export QUAY_PORT=8443
export QUAY_USER=admin
export QUAY_PWD=admin123456
export QUAY_TOKEN=$(echo -n $QUAY_USER:$QUAY_PWD | base64)
export MIRROR_REPO=mirror
----


.imageSetConfiguration-v2-4.16.16.yaml
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.16
      minVersion: 4.16.16
      maxVersion: 4.16.17
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
      packages:
       - name: kubevirt-hyperconverged
       - name: mtv-operator
       - name: local-storage-operator
       - name: lvms-storage-operator
       - name: kubernetes-nmstate-operator
       - name: web-terminal
  additionalImages:
  - name: quay.io/edge-infrastructure/assisted-installer-agent:latest
  - name: quay.io/edge-infrastructure/assisted-installer:latest
  - name: quay.io/edge-infrastructure/assisted-installer-controller:latest
  - name: quay.io/sclorg/postgresql-12-c8s:latest
  - name: quay.io/edge-infrastructure/assisted-image-service:latest
  - name: quay.io/edge-infrastructure/assisted-service:latest
  - name: quay.io/edge-infrastructure/assisted-service:latest
  - name: quay.io/edge-infrastructure/assisted-installer-ui:latest
  - name: quay.io/openshift-release-dev/ocp-release:4.16.16-x86_64
  - name: quay.io/karmab/aicli:latest
  - name: registry.redhat.io/rhel9/support-tools:latest
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/openshift4/ose-cli:latest
  - name: registry.redhat.io/ubi9/ubi:latest

----

If you need OS iamges for Openshift Virtualization, add the following under "additionalImages:". Select which is appropite.

NOTE: For more images - see https://quay.io/organization/containerdisks

----
  - name: quay.io/containerdisks/centos-stream:9
  - name: quay.io/containerdisks/fedora:latest
  - name: registry.redhat.io/rhel8/rhel-guest-image:latest
  - name: registry.redhat.io/rhel9/rhel-guest-image:latest
----

Sample for 4.19

.imageSetConfiguration-v2-4.19.12.yaml
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.19
      minVersion: 4.19.12
      maxVersion: 4.16.12
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages:
       - name: kubevirt-hyperconverged
       - name: mtv-operator
       - name: local-storage-operator
       - name: lvms-storage-operator
       - name: kubernetes-nmstate-operator
       - name: web-terminal
  additionalImages:
  - name: quay.io/containerdisks/centos-stream:9
  - name: quay.io/containerdisks/fedora:latest
  - name: registry.redhat.io/rhel8/rhel-guest-image:latest
  - name: registry.redhat.io/rhel9/rhel-guest-image:latest
---- 

=== Login into All registries.

Download the pull secret from https://console.redhat.com/openshift/downloads and create a file pull-secret.txt in home folder on the connected host. (original file, if downloaded, is pull-secret.txt)


.Create auth.json
----
podman login --authfile local.json -u $QUAY_USER -p $QUAY_PWD $QUAY_HOST_NAME:$QUAY_PORT --tls-verify=false 
jq -cM -s '{"auths": ( .[0].auths + .[1].auths ) }' local.json ~/pull-secret.txt > pull-secret.json
podman login --authfile ./pull-secret.json quay.io
podman login --authfile ./pull-secret.json registry.redhat.io
podman login --authfile ./pull-secret.json $QUAY_HOST_NAME:$QUAY_PORT

----

=== Direct Registry to Registry mirror

.Mirror Direct
----
mkdir ~/working-dir
cp imageSetConfiguration-v2-4.16.16.yaml ~/working-dir
cd ~/working-dir
oc mirror -c imageSetConfiguration-v2-4.16.16.yaml --workspace file://$PWD docker://$QUAY_HOST_NAME:$QUAY_PORT/$MIRROR_REPO --v2
----

=== Mirror to file system

.Mirror to file system
----
mkdir working-dir
cd working-dir
oc mirror -config ../imageset-config.yaml file://./data
----


=== Populating Pull Through Cache

To populate a pull through cahe, set the local registries.coonf to reflect remote repositories:

./etc/containers/registries.conf
----
unqualified-search-registries = ["registry.access.redhat.com", "docker.io"]
short-name-mode = ""
additional-layer-store-auth-helper = ""

[[registry]]
  prefix = ""
  location = "docker.io"

  [[registry.mirror]]
    location = "remote.cache.com/dockeriocache"
    pull-from-mirror = "digest-only"

  [[registry.mirror]]
    location = "remote.cache.com/dockeriocache"
    pull-from-mirror = "tag-only"

[[registry]]
  prefix = ""
  location = "quay.io"

  [[registry.mirror]]
    location = "remote.cache.com/cachequayio"
    pull-from-mirror = "digest-only"

  [[registry.mirror]]
    location = "remote.cache.com/cachequayio"
    pull-from-mirror = "tag-only"

[[registry]]
  prefix = ""
  location = "registry.redhat.io"

  [[registry.mirror]]
    location = "remote.cache.com/registryredhatiocache"
    pull-from-mirror = "digest-only"

  [[registry.mirror]]
    location = "remote.cache.com/registryredhatiocache"
    pull-from-mirror = "tag-only"
----