== Mirror using oc-mirror v1

=== Get the binaries:

Install relevant binaries on connected, and disconnected hosts. For example mirror registry would only be needed on the disconnected host. 

TIP: All configuration was done for OpenShift 4.16.16. Update according to your target version.

.Install nmstatectl, get openshift binaries, and mirror registry
----
sudo dnf install -y nmstate
mkdir ~/bin
cd ~/bin
cd ~/bin
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz 
wget https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/oc-mirror.rhel9.tar.gz
tar zxvf openshift-client-linux.tar.gz
tar zxvf oc-mirror.rhel9.tar.gz
chmod +x oc-mirror
rm *.gz
----

.env.sh
----
export QUAY_HOST_NAME=quayhostname
export QUAY_PORT=8443
export QUAY_USER=admin
export QUAY_PWD=admin123456
export QUAY_TOKEN=$(echo -n $QUAY_USER:$QUAY_PWD | base64)
export MIRROR_REPO=mirror
----

.Create working directory
----
mkdir mirror
cd mirror
----


.imageset.yaml
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: /home/openshift/mirror
mirror:
  platform:
    channels:
    - name: stable-4.16
      type: ocp
      minVersion: 4.16.16
      maxVersion: 4.16.16
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: kubevirt-hyperconverged
      channels:
      - name: stable
        minVersion: 4.16.3
    - name: mtv-operator
      channels:
        - name: release-v2.7
    - name: local-storage-operator
      channels:
        - name: stable
    - name: lvms-operator
      channels:
        - name: stable-4.16
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: web-terminal
      channels:
      - name: fast

    - name: cincinnati-operator
      channels:
        - name: v1

  additionalImages:
    - name: quay.io/edge-infrastructure/assisted-installer-agent:latest
  - name: quay.io/edge-infrastructure/assisted-installer:latest
  - name: quay.io/edge-infrastructure/assisted-installer-controller:latest
  - name: quay.io/sclorg/postgresql-12-c8s:latest
  - name: quay.io/edge-infrastructure/assisted-image-service:latest
  - name: quay.io/edge-infrastructure/assisted-installer-ui:latest
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: registry.redhat.io/rhel8/support-tools
  - name: registry.redhat.io/rhel9/support-tools
  - name: registry.redhat.io/openshift4/ose-must-gather:latest
  - name: quay.io/openshift-release-dev/ocp-release:4.16.16-x86_64

----

If you need OS iamges for Openshift Virtualization, add the following under "additionalImages:". Select which is appropite.

NOTE: For more images - see https://quay.io/organization/containerdisks

.additionalImages
----
  - name: quay.io/containerdisks/centos-stream:9
  - name: quay.io/containerdisks/fedora:latest
  - name: registry.redhat.io/rhel8/rhel-guest-image:latest
  - name: registry.redhat.io/rhel9/rhel-guest-image:latest
----

=== Login into All registries.

Download the pull secret from https://console.redhat.com/openshift/downloads and create a file pull-secret.txt in home folder on the connected host. (original file, if downloaded, is pull-secret.txt)


.Create auth.json
----
podman login --authfile local.json -u $QUAY_USER -p $QUAY_PWD $QUAY_HOST_NAME:$QUAY_PORT --tls-verify=false 
jq -cM -s '{"auths": ( .[0].auths + .[1].auths ) }' local.json ~/pull-secret.txt > pull-secret.json
podman login --authfile ./pull-secret.json quay.io
podman login --authfile ./pull-secret.json registry.redhat.io
podman login --authfile ./pull-secret.json $QUAY_HOST_NAME:$QUAY_PORT
----

== Disconnected 
----
cd ~/mirror
mkdir data
oc mirror --config=imageset-config.yaml file://./data
----

Move the contents of ~/mirror to remote host. Follow the instructions above to install binaries and login into mirror registry.

.On remote host execute:
----
cd ~/mirror
mkdir data
oc mirror --from=./data/ docker://$QUAY_HOST_NAME:$QUAY_PORT/$MIRROR_REPO
----