:toc2:

== Single Node Base Image Seed Cluster

A Seed cluster is the default template for the clusters you want to create, using the Image Based Installer.

The only big difference between standard cluster install, is the mounting of /var/lib/containers partition, labelled "varlibcontainers" and can be placed on any disk.

After configuration of the seed cluster with operators and configurations required, we use the Life Cycle Agent Operator to capture the state of the cluster into an seed image.

This seed image, is then used to create clusters, with pre-seeded operators and configurations.


=== Create a cluster with a mounted /var/lib/containers Partition

Follow the guide https://www.redhat.com/en/blog/a-guide-to-creating-a-separate-disk-partition-at-installation-time

Adding a partition to an existing cluster is also possible - https://access.redhat.com/solutions/4952011

=== Install Life Cycle Agent

.lifecycleagent.yaml
[source,yaml]
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lifecycle-agent
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-lifecycle-agent
  namespace: openshift-lifecycle-agent
spec:
  targetNamespaces:
  - openshift-lifecycle-agent
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-lifecycle-agent
  namespace: openshift-lifecycle-agent
spec:
  targetNamespaces:
  - openshift-lifecycle-agent
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-lifecycle-agent-subscription
  namespace: openshift-lifecycle-agent
spec:
  channel: "stable"
  name: lifecycle-agent
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---

----

=== 98-var-partition Machine Config

Confirm the 90-var-partition machine config, which was configured during the cluster install:

.Query machine config
[source,bash]
----
oc get machineconfig 98-var-partition -o yaml -no-managedfields
----

Output should be similar to:

.98-var-partition.yaml
[source,yaml]
----
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: "2025-06-20T22:04:35Z"
  generation: 1
  labels:
    machineconfiguration.openshift.io/role: master
  name: 98-var-partition
  resourceVersion: "2036"
  uid: 31dc684b-9540-4f43-8de4-b21419722c55
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      disks:
      - device: /dev/vdb
        partitions:
        - label: varlibcontainers
          sizeMiB: 150000
          startMiB: 220000
      filesystems:
      - device: /dev/disk/by-partlabel/varlibcontainers
        format: xfs
        mountOptions:
        - defaults
        - prjquota
        path: /var/lib/containers
    systemd:
      units:
      - contents: |-
          # Generated by Butane
          [Unit]
          Before=local-fs.target
          Requires=systemd-fsck@dev-disk-by\x2dpartlabel-varlibcontainers.service
          After=systemd-fsck@dev-disk-by\x2dpartlabel-varlibcontainers.service

          [Mount]
          Where=/var/lib/containers
          What=/dev/disk/by-partlabel/varlibcontainers
          Type=xfs
          Options=defaults,prjquota

          [Install]
          RequiredBy=local-fs.target
        enabled: true
        name: var-lib-containers.mount
----

=== Install and configure operators

Install and configure operators as required. Keep in mind that any configuration requiring any resources, like networking and storage, are not allowed.

WARNING: At the moment only IPV4 is supported.

WARNING: Do need install any ACM related artifacts, ie. don't register cluster with ACM.

=== Capture the Seed Image

==== Pull Secret including your target image registry credentials

.Create a base64 encoded secret:
[source,bash]
----
podman login --authfile local.json -u $QUAY_USER -p $QUAY_PWD $QUAY_HOST_NAME:$QUAY_PORT --tls-verify=false
jq -cM -s '{"auths": ( .[0].auths + .[1].auths ) }' local.json pull-secret.txt > pull-secret.json
podman login --authfile ./pull-secret.json quay.io
podman login --authfile ./pull-secret.json registry.redhat.io
podman login --authfile ./pull-secret.json $QUAY_HOST_NAME:$QUAY_PORT
base64encode -w 0 ./pull-secret.json; echo
----

.seedgen-secret.yaml
----
apiVersion: v1
kind: Secret
metadata:
  name: seedgen 
  namespace: openshift-lifecycle-agent
type: Opaque
data:
  seedAuth: <encoded output above>
----

==== Start the Seed Generator

Seed generator is started when the SeedGenerator CR is created. 

The status of the CR, indicates the state of the operator, but will you will loose connection the API server during the creation process. 

NOTE: After a few minutes, and creation of the image on the specified registry, you would be able to see the final status.

.seedgenerator.yaml
[source,yaml]
----
apiVersion: lca.openshift.io/v1
kind: SeedGenerator
metadata:
  name: seedimage 
spec:
  seedImage: <registry/myrepo/seed-container-sno:4.19.2> 
----


